doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:

            UserVO:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Database/ORM/VO'
                prefix: 'App\User\Domain\Aggregate\User\VO'
                alias: App

            SharedVO:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM/VO'
                prefix: 'App\Shared\Domain\VO'
                alias: App

            ProductCatalogVO:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ProductCatalog/Infrastructure/Database/ORM/VO'
                prefix: 'App\ProductCatalog\Domain\VO'
                alias: App

            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Database/ORM/Entity'
                prefix: 'App\User\Domain\Aggregate\User\Entity'
                alias: App

            Category:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ProductCatalog/Domain/Aggregate/Category'
                prefix: 'App\ProductCatalog\Domain\Aggregate\Category'
                alias: App

            Product:
                type: xml
                dir: '%kernel.project_dir%/src/ProductCatalog/Infrastructure/Database/ORM/Aggregate/Product'
                prefix: 'App\ProductCatalog\Domain\Aggregate\Product\Entity'
                alias: App

            Review:
                type: xml
                dir: '%kernel.project_dir%/src/ProductCatalog/Infrastructure/Database/ORM/Aggregate/Review'
                prefix: 'App\ProductCatalog\Domain\Aggregate\Review\Entity'
                alias: App

            Discount:
                type: xml
                dir: '%kernel.project_dir%/src/ProductCatalog/Infrastructure/Database/ORM/Aggregate/Discount'
                prefix: 'App\ProductCatalog\Domain\Aggregate\Discount\Entity'
                alias: App

            OrderVO:
                type: xml
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Database/ORM/VO'
                prefix: 'App\Order\Domain\Aggregate\Order\VO'
                alias: App

            Order:
                type: xml
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Database/ORM/Entity'
                prefix: 'App\Order\Domain\Aggregate\Order\Entity'
                alias: App

            GedmoTree:
                type: attribute
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                is_bundle: false
        controller_resolver:
            auto_mapping: true


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
