
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_DB:  "store"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  hoverfly:
    container_name: hoverfly
    image: spectolabs/hoverfly:v1.3.4
    command:
      - "-webserver"
      - "-response-body-files-path=/hoverfly_app/response"
      - "-import=/hoverfly_app/simulation/recommend.simulation.json"
    volumes:
      - "C:/OSPanel/domains/store/hoverfly:/hoverfly_app:ro"
    ports:
      - "8500:8500"